
photo_manager :
  enabled: true
#  images_path: "/photo_manager"
#  raw_images_path: "/raw"
#  ressources_path: "/ressources"

  tasks:
    metadatas: # was photoMetadata
      enabled: true
      set_copyright: true
      set_author: true
      author: David Jacquel
      prompted_metadatas:
      # - title
      # - location

    orientation:
      enabled: false

    resize:
      enabled: false
      sizes:
        - 1024
        - 250

    signature:
      enabled: false
      signature_file: /img/signature-david-jacquel.svg

    tags:
      enabled: false

    watermark:
      enabled: false
      watermark_file: /img/watermark.svg

    post:
      enabled: false
