
photo_manager :
  enabled: true
  images_path: /img
  raw_images_path: /photo_manager

  tasks:

    metadatas: # was photoMetadata
      enabled: true
      set_copyright: true
      set_author: true
      author: David Jacquel
      prompted_metadatas:
      # - title
      # - location

    orientation:
      enabled: true

    resize:
      enabled: true
      sizes:
        - 1024
        - 250

    signature:
      enabled: true
      signature_file: /img/signature-david-jacquel.svg

    tags:
      enabled: false

    watermark:
      enabled: false
      watermark_file: /img/watermark.svg

    post:
      enabled: false
