# daja-art.fr setup

title: DaJa Art
description: David Jacquel - Photographie

language: fr
timezone: Europe/Paris

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

email: dj[AT]daja-art[POINT]fr
twitter_username: djacquel
github_username:  djacquel

# Build settings
permalink: pretty

kramdown:
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   smart_quotes: lsquo,rsquo,ldquo,rdquo
#   use_coderay: false
    parse_block_html: true # instruct kramdown to parse inside html block elements like p, header, lists, ...
    parse_span_html: true
#   coderay:
#     coderay_wrap: div
#     coderay_line_numbers: inline
#     coderay_line_numbers_start: 1
#     coderay_tab_width: 4
#     coderay_bold_every: 10
#     coderay_css: style

excerpt_separator: "<!--more-->"

sass:
  # loading path from site root
  # default to _sass
  # sass_dir: node_modules/bootstrap/scss

  # multiple load paths
  # doesn't work in safe mode (github pages)
  # load_paths:
  #   - path1
  #   - path2

  # style : nested (default), compact, compressed, expanded
  #         :nested, :compact, :compressed, :expanded also works
  # see http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  style: nested

defaults:
  - { scope: { type: posts }, values: { layout: post } }
  - { scope: { type: pages }, values: { layout: page } }

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# debug liquid unused variables and filters
#  + error management
liquid:
  strict_variables: false # default: false
  strict_filters: true # default: false
  error_mode: strict # default: warn
